// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"github.com/MrtnOmwenga/incident-tracking/backend/pkg/controllers"
	"github.com/MrtnOmwenga/incident-tracking/backend/pkg/repositories"
	"github.com/MrtnOmwenga/incident-tracking/backend/pkg/services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Init(db *gorm.DB) (*AppContainer, error) {
	repositoryContainer := repositories.NewRepositoryContainer(db)
	serviceContainer := services.NewServiceContainer(repositoryContainer)
	controllerContainer := controllers.NewControllerContainer(serviceContainer)
	router := ProvideRouter()
	appContainer := ProvideAppContainer(controllerContainer, serviceContainer, repositoryContainer, router)
	return appContainer, nil
}
