# The production cluster: the base, plus the settings that differ per deployment (the two .env
# files) and the image tags, which Flux updates as new images are published.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
configMapGenerator:
  - name: lighthouse-config
    namespace: lighthouse
    envs: [lighthouse.env]
  - name: ghostchat-config
    namespace: demos
    envs: [ghostchat.env]
images:
  - name: ghcr.io/mrtnomwenga/lighthouse
    newTag: main # {"$imagepolicy": "flux-system:lighthouse:tag"}
  - name: ghcr.io/mrtnomwenga/rbac-api
    newTag: main # {"$imagepolicy": "flux-system:rbac-api:tag"}
  - name: ghcr.io/mrtnomwenga/ghostchat
    newTag: main # {"$imagepolicy": "flux-system:ghostchat:tag"}
